### ISSUE TITLE
Django vulnerability found in 1-Django/requirements.txt

### ISSUE THREAD

**Issue by ahmetuysal** [koltpython/python-workshops#2]
### Security Alert
Upgrade Django to version 2.2.9 or later. For example:

`Django>=2.2.9
`

**Details**
moderate severity
Vulnerable versions: >= 2.0.0, < 2.2.9
Patched version: 2.2.9
Django before 1.11.27, 2.x before 2.2.9, and 3.x before 3.0.1 allows account takeover. A suitably crafted email address (that is equal to an existing user's email address after case transformation of Unicode characters) would allow an attacker to be sent a password reset token for the matched user account. (One mitigation in the new releases is to send password reset tokens only to the registered user email address.)

**Comment by firattamur** [comment]
Requirement.txt django version changed to 2.2.9
